server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Evita l'errore 404 ricaricando la pagina su un'architettura a singola pagina (SPA)
        try_files $uri $uri/ /index.html;
    }
}