services:
  api-gestione-fatture:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_fatture_gruppocr
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - GENERIC_TIMEZONE=Europe/Rome
    volumes:
      - ./backend/data:/app/data
      - ./fatture_da_leggere:/fatture
      - ./fatture_lette:/fatture_lette
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend-gestione-fatture:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_fatture_gruppocr
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api-gestione-fatture

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_automations
    user: "root"
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Rome
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_RESTRICT_FILE_ACCESS_TO=/fatture;/fatture_lette
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_HIDE_USAGE_PAGE=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=false
    volumes:
      - ./n8n_config:/home/node/.n8n
      - ./fatture_da_leggere:/fatture
      - ./fatture_lette:/fatture_lette
    extra_hosts:
      - "host.docker.internal:host-gateway"
